#!/usr/bin/env python3
"""Create the smallest project-local harness from a harness plan."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


SCRIPTED_CHECK = '''#!/usr/bin/env python3
"""Smoke check generated by Vision Product Loop."""

from __future__ import annotations

from pathlib import Path


def main() -> None:
    vision = Path("VISION.md")
    if not vision.is_file():
        raise SystemExit("VISION.md is missing")
    print("vision smoke check passed")


if __name__ == "__main__":
    main()
'''


NODE_CHECK = '''const fs = require("fs");

if (!fs.existsSync("VISION.md")) {
  console.error("VISION.md is missing");
  process.exit(1);
}

console.log("vision smoke check passed");
'''


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_file(path: Path, content: str, apply: bool, force: bool) -> dict[str, Any]:
    exists = path.exists()
    if exists and not force:
        return {
            "path": str(path),
            "action": "skipped",
            "reason": "exists",
        }
    if apply:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return {
        "path": str(path),
        "action": "written" if apply else "planned",
        "reason": "force" if exists and force else "new",
    }


def update_package_script(
    root: Path,
    script_name: str,
    command: str,
    apply: bool,
    force: bool,
) -> dict[str, Any]:
    package_path = root / "package.json"
    package = load_json(package_path) if package_path.is_file() else {}
    scripts = package.setdefault("scripts", {})
    if not isinstance(scripts, dict):
        return {
            "path": str(package_path),
            "action": "skipped",
            "reason": "scripts field is not an object",
        }
    if script_name in scripts and not force:
        return {
            "path": str(package_path),
            "action": "skipped",
            "reason": "script exists",
        }
    scripts[script_name] = command
    if apply:
        package_path.write_text(json.dumps(package, indent=2) + "\n", encoding="utf-8")
    return {
        "path": str(package_path),
        "action": "written" if apply else "planned",
        "reason": "package-script",
    }


def create_harness(
    root: Path,
    plan: dict[str, Any],
    apply: bool = False,
    force: bool = False,
) -> dict[str, Any]:
    """Create a missing harness from a plan. By default this is a dry_run."""
    root = root.resolve()
    recommended = plan.get("recommended", {})
    kind = recommended.get("kind")
    dry_run = not apply
    changes: list[dict[str, Any]] = []

    if plan.get("strategy") == "reuse-existing-harness":
        return {
            "dry_run": dry_run,
            "strategy": "reuse-existing-harness",
            "changes": [],
            "next_action": "Run the recommended existing harness.",
        }

    if kind == "new-package-script":
        script_path = root / "scripts" / "vision_smoke_check.js"
        changes.append(write_file(script_path, NODE_CHECK, apply, force))
        changes.append(
            update_package_script(
                root,
                recommended.get("name", "test:vision"),
                "node scripts/vision_smoke_check.js",
                apply,
                force,
            )
        )
        command = recommended.get("command", "npm run test:vision")
    elif kind == "new-python-test":
        test_path = root / "tests" / "test_vision_slice.py"
        content = (
            "from pathlib import Path\n\n\n"
            "def test_vision_contract_exists():\n"
            "    assert Path('VISION.md').is_file()\n"
        )
        changes.append(write_file(test_path, content, apply, force))
        command = "python3 -m unittest discover"
    else:
        script_path = root / "scripts" / "vision_smoke_check.py"
        changes.append(write_file(script_path, SCRIPTED_CHECK, apply, force))
        command = recommended.get("command", "python3 scripts/vision_smoke_check.py")

    return {
        "dry_run": dry_run,
        "strategy": "create-minimal-harness",
        "changes": changes,
        "command": command,
        "next_action": "Run the created harness before claiming progress.",
    }


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Create the smallest missing harness from a harness plan."
    )
    parser.add_argument("--root", default=".", help="Project root where the harness belongs.")
    parser.add_argument("--plan", required=True, help="Path to JSON output from plan_harness.py.")
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Write files. Without this flag, create_harness.py performs a dry-run.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing harness files or scripts when applying.",
    )
    args = parser.parse_args()

    plan = load_json(Path(args.plan))
    result = create_harness(Path(args.root), plan, apply=args.apply, force=args.force)
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
